add logging
uwcirg/asbi-screening-app pull request #70
Opened 2022-12-01 23:15 UTC by achen2401

https://www.pivotaltracker.com/story/show/183765514

2022-12-07 17:58 UTC, ivan-c approved these changes
Looks good! Had a nitpick on a log message, but ready to merge

2022-12-07 17:58 UTC, ivan-c commented on src/util/log.js
> +    console.log("confidential backend URL is not set.");
Always appreciate when a config is optional! 

If I understand correctly, if `VUE_APP_CONF_API_URL` is unconfigured, no logging will occur. 

Just added some clarification:

```suggestion
    console.log("audit log skipped; confidential backend URL is not set");
```

2022-12-07 18:31 UTC, mcjustin reviewed
@achen2401  Thanks for detailing your proposed logging in the description here. I'd like to change some of it. It's tough for me to comment on in this format, let's bring it to the google doc and iterate on it a bit more there https://docs.google.com/document/d/1ZFjw97hf16uM2d2j-zQx9n30ycbKxuzEk6mhSWWxTuk/edit#heading=h.mnk81sbw6z3

2023-01-11 20:12 UTC, pbugni requested changes
Great work @achen2401 
Would you mind looking at the https://github.com/uwcirg/logserver README?  Your format looks great, but we should bring several system identifiers up one level and include in the `message` element only the portions that relate to the action/event being logged.

2023-01-11 21:10 UTC, achen2401 commented
thanks @pbugni I made the changes and please see the description for this PR with updated example posted JSON.  Let me know if you see any issue with my changes.

2023-02-01 22:23 UTC, pbugni approved these changes
Nice work!  Add error logging as you see fit.

2023-02-01 22:23 UTC, pbugni commented on src/components/Survey.vue
> +      ).catch((e) => console.log("Get care plan error ", e));
if this is just debugging info, no worries, but it would be of value to add error logging here and elsewhere to capture client problems.

2023-02-02 00:42 UTC, mcjustin approved these changes

2023-02-02 04:23 UTC, merged